{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-no-op
  version: {{ version }}

source:
  path: ../..

build:
  script: python setup.py install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - nodejs

  run:
    - python {{ python }}
    - qiime2

test:
  imports:
    - q2_no_op
    - qiime2.plugins.no_op

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
