name: busywork

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: fetch source
        uses: actions/checkout@v2
        with:
          path: source

      - name: set up miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.6

      - name: set up conda build
        run: conda install -n base -q -y -c defaults --override-channels conda-build conda-verify

      - name: build conda package
        run: |
          cd source
          conda build \
            -c https://conda.anaconda.org/conda-forge \
            -c https://conda.anaconda.org/bioconda \
            -c https://conda.anaconda.org/qiime2 \
            -c defaults \
            --override-channels --output-folder ../package ci/recipe

      - name: zip built package
        run: zip -r ./package.zip ./package

      - name: store built package
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: ./package.zip

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: fetch built package
        uses: actions/download-artifact@v1
        with:
          name: package

      - name: debug
        run: ls -lah

      - name: unzip built package
        run: unzip ./package/package.zip

      - name: debug
        run: ls -lah package/package

      - name: create conda testing env
        run: conda create -q -y -p ./test-env

      - name: install plugin and dependencies
        run: |
          conda install -p ./test-env -q -y \
            -c ./package/package \
            -c https://conda.anaconda.org/conda-forge \
            -c https://conda.anaconda.org/bioconda \
            -c https://conda.anaconda.org/qiime2 \
            -c defaults \
            --override-channels q2-no-op pytest nose