name: build-test
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build-and-test-example-plugin:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: qiime2/action-library-packaing@alpha1
      with: 
        plugin-name: q2-no-op
        additional-tests: pytest --pyargs q2_no_op
