on: [push]

jobs:
  qiime2_job:
    runs-on: ubuntu-latest
    name: conda packaging
    steps:
      # This checkout is only necessary for "private" actions
      - name: Checkout
        uses: actions/checkout@v2
      - name: Busywork
        uses: ./.github/actions/busywork
