on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # This checkout is only necessary for "private" actions
      - name: Checkout
        uses: actions/checkout@v2
      - name: Busywork
        uses: ./.github/actions/busywork
